export const alphabet = [
    { letter: "a", flag: false },
    { letter: "b", flag: false },
    { letter: "c", flag: false },
    { letter: "d", flag: false },
    { letter: "e", flag: false },
    { letter: "f", flag: false },
    { letter: "g", flag: false },
    { letter: "h", flag: false },
    { letter: "i", flag: false },
    { letter: "j", flag: false },
    { letter: "k", flag: false },
    { letter: "l", flag: false },
    { letter: "m", flag: false },
    { letter: "n", flag: false },
    { letter: "o", flag: false },
    { letter: "p", flag: false },
    { letter: "q", flag: false },
    { letter: "r", flag: false },
    { letter: "s", flag: false },
    { letter: "t", flag: false },
    { letter: "u", flag: false },
    { letter: "v", flag: false },
    { letter: "w", flag: false },
    { letter: "x", flag: false },
    { letter: "y", flag: false },
    { letter: "z", flag: false },
  ];

 